# Generated by Django 5.2.5 on 2025-08-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('categoria', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_alta', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
