# Generated by Django 5.2.5 on 2025-08-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='nombre_apellido',
        ),
        migrations.AddField(
            model_name='socio',
            name='apellido',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socio',
            name='nombre',
            field=models.CharField(default='nombre', max_length=50),
            preserve_default=False,
        ),
    ]
