# Generated by Django 5.2.5 on 2025-08-21 02:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_categoria_alter_socio_options_alter_socio_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='socios', to='socios.categoria'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('mes_correspondiente', models.CharField(help_text='Mes al que corresponde el pago (ej: Enero 2025)', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('debito', 'Débito'), ('credito', 'Crédito')], default='efectivo', max_length=15)),
                ('comprobante', models.CharField(blank=True, help_text='Número de comprobante o referencia', max_length=100, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='socios.socio')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
