# Generated by Django 5.2.5 on 2025-08-25 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0006_socio_es_administrador_socio_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_antiguos', to='socios.concepto'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='mes_correspondiente',
            field=models.CharField(blank=True, help_text='Mes al que corresponde el pago (ej: Enero 2025)', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Formato: MMYY (ej: 0124 para enero 2024)', max_length=4, unique=True)),
                ('mes', models.IntegerField(help_text='Mes (1-12)')),
                ('anio', models.IntegerField(help_text='Año completo (ej: 2024)')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='socios.concepto')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('mes', 'anio', 'concepto')},
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='cuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='socios.cuota'),
        ),
    ]
