# Generated by Django 5.2.5 on 2025-09-12 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0007_alter_pago_concepto_alter_pago_mes_correspondiente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='es_pago_multiple',
            field=models.BooleanField(default=False, help_text='Indica si este pago cubre múltiples cuotas'),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_saldo_usado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto de saldo a favor usado en este pago', max_digits=10),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_sobrante',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto sobrante que se agrega al saldo del socio', max_digits=10),
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, help_text='Monto del pago aplicado a esta cuota específica', max_digits=10)),
                ('monto_restante', models.DecimalField(decimal_places=2, default=0, help_text='Monto restante de la cuota después de aplicar el pago', max_digits=10)),
                ('pagado_completamente', models.BooleanField(default=False)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='socios.cuota')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='socios.pago')),
            ],
            options={
                'verbose_name': 'Detalle de Pago',
                'verbose_name_plural': 'Detalles de Pago',
                'unique_together': {('pago', 'cuota')},
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='cuotas',
            field=models.ManyToManyField(blank=True, related_name='pagos_multiples', through='socios.DetallePago', to='socios.cuota'),
        ),
        migrations.CreateModel(
            name='SaldoSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, help_text='Saldo actual del socio. Positivo = saldo a favor, Negativo = debe', max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('socio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saldo', to='socios.socio')),
            ],
            options={
                'verbose_name': 'Saldo de Socio',
                'verbose_name_plural': 'Saldos de Socios',
            },
        ),
        migrations.CreateModel(
            name='MovimientoSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('pago_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socios.pago')),
                ('saldo_socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='socios.saldosocio')),
            ],
            options={
                'verbose_name': 'Movimiento de Saldo',
                'verbose_name_plural': 'Movimientos de Saldo',
                'ordering': ['-fecha'],
            },
        ),
    ]
