# Generated by Django 5.2.5 on 2025-09-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0008_pago_es_pago_multiple_pago_monto_saldo_usado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('debito', 'Débito'), ('credito', 'Crédito'), ('saldo_favor', 'Saldo a favor')], default='efectivo', max_length=15),
        ),
    ]
