# Generated by Django 5.2.5 on 2025-08-25 02:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0007_alter_pago_concepto_alter_pago_mes_correspondiente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], help_text='Tipo de movimiento: Ingreso o Egreso', max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Movimiento',
                'verbose_name_plural': 'Categorías de Movimientos',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('descripcion', models.TextField(help_text='Descripción detallada del movimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(help_text='Categoría del movimiento', on_delete=django.db.models.deletion.PROTECT, to='caja.categoriamovimiento')),
                ('pago', models.OneToOneField(blank=True, help_text='Pago asociado (solo para ingresos por cuotas)', null=True, on_delete=django.db.models.deletion.CASCADE, to='socios.pago')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SaldoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_egresos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Saldo de Caja',
                'verbose_name_plural': 'Saldos de Caja',
                'ordering': ['-fecha_fin'],
                'unique_together': {('fecha_inicio', 'fecha_fin')},
            },
        ),
    ]
